
Alias /images/ "/var/www/images/"

<IfModule mod_ssl.c>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/tests
	SSLCertificateFile	/etc/dehydrated/cert.pem
	SSLCertificateKeyFile	/etc/dehydrated/privkey.pem
	SSLCertificateChainFile /etc/dehydrated/chain.pem

	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost

		<Location /result>
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>

		<Location /admin>
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>

		DocumentRoot /var/www/html

		<FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">
			Header set Access-Control-Allow-Origin "*"
		</FilesMatch>

		SSLEngine on

		<FilesMatch "\.(php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName anonymous.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName assurance.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName cocov2.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName noec.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName pseudonymous.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName personalized.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName rands.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

	<VirtualHost _default_:443>
		ServerName esi.release-check.example.org

		<Location />
			AuthType shibboleth
			ShibRequestSetting requireSession true
			ShibRequestSetting entityIDSelf https://$hostname/shibboleth
			require shib-session
		</Location>
		SSLEngine on
	</VirtualHost>

</IfModule>